# Generated by Django 4.2.23 on 2025-06-15 11:37

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/user.jpeg', storage=django.core.files.storage.FileSystemStorage(base_url='/storages/images/', location=pathlib.PurePosixPath('/home/4frag/my_files/projects/mai_cf/backend/storages/images')), upload_to='', verbose_name='avatars'),
        ),
    ]
