# Generated by Django 4.2.23 on 2025-06-13 15:08

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='titles')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='prices')),
                ('author', models.CharField(verbose_name='authors')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/4frag/my_files/projects/mai_cf/backend/storages/images')), upload_to='', verbose_name='images')),
                ('link', models.URLField(verbose_name='links')),
            ],
        ),
    ]
