# Generated by Django 4.2.23 on 2025-06-15 23:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_completedcourses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedCourses',
            new_name='CompletedCourse',
        ),
    ]
